const cases = [
  {
    id: 1,
    case_no: "CaseNo1",
    case_date: "01/19/2024",
    case_address: "921 Thurstin st apt#46 , Bowling Green OH, 43402",
    case_violation: "Illegal construction",
    case_description: "Apartment structure does not meet minimum regulations",
    video: "video.mp4",
    image: "image.png",
  },
  {
    id: 2,
    case_no: "CaseNo2",
    case_date: "01/19/2024",
    case_address: "921 Thurstin st apt#46 , Bowling Green OH, 43402",
    case_violation: "Illegal construction",
    case_description: "Apartment structure does not meet minimum regulations",
    video: "video.mp4",
    image: "image.png",
  },
  {
    id: 3,
    case_no: "CaseNo3",
    case_date: "01/19/2024",
    case_address: "921 Thurstin st apt#46 , Bowling Green OH, 43402",
    case_violation: "Illegal construction",
    case_description: "Apartment structure does not meet minimum regulations",
    video: "video.mp4",
    image: "image.png",
  },
  {
    id: 4,
    case_no: "CaseNo4",
    case_date: "01/19/2024",
    case_address: "921 Thurstin st apt#46 , Bowling Green OH, 43402",
    case_violation: "Illegal construction",
    case_description: "Apartment structure does not meet minimum regulations",
    video: "video.mp4",
    image: "image.png",
  },
  {
    id: 5,
    case_no: "CaseNo5",
    case_date: "01/19/2024",
    case_address: "921 Thurstin st apt#46 , Bowling Green OH, 43402",
    case_violation: "Illegal construction",
    case_description: "Apartment structure does not meet minimum regulations",
    video: "video.mp4",
    image: "image.png",
  },
  {
    id: 6,
    case_no: "CaseNo6",
    case_date: "01/19/2024",
    case_address: "921 Thurstin st apt#46 , Bowling Green OH, 43402",
    case_violation: "Illegal construction",
    case_description: "Apartment structure does not meet minimum regulations",
    video: "video.mp4",
    image: "image.png",
  },
];

export default {
  cases,
};
