export default {
  INSPECTION: "Inspection",
  REPORTS: "Reports",
  NOTIFICATIONS: "Notifications",
  HELP: "Help",
  OPEN_NEW_CASE: "OpenNewCase",
  ACTIVE_CASE: "ActiveCase",
  ACTIVE_CASE_DETAILS: "ActiveCaseDetails",
  ACTIVE_CASE_ON_MAP: "ActiveCaseOnMap",
  GET_STARTED: "GetStarted",
  CONTACT_US: "ContactUs",
  DESIGN_HELP: "DesignHelp",
  FAQ: "FAQ",
  SETTINGS: "Settings",
  ACKNOWLEDEMENTS: "Acknowledements",
  LOGIN: "Login",
  PRIVACY_POLICY: "PrivacyPolicy",
  TAB: "Tab",
  CUSTOM_DRAWER: "CustomDrawer",
  EDIT_ACTIVE_CASE: "EditActiveCase",
};
